### ISSUE TITLE
Players leaving active game script crash

### ISSUE THREAD

**Issue by MMeent** [nailed/nailed#43]
Leaving an active game which uses the playerlist in its script can crash that game script

**Comment by jk-5** [comment]
See https://github.com/nailed/mappack-nail/issues/1
This is not really a nailed issue, but we need to build something in nailed to prevent this

**Comment by jk-5** [comment]
Fixed by https://github.com/nailed/mappack-nail/commit/7d20e9a507f138f785c88b98303a039295a7986f and https://github.com/nailed/nailed/commit/e0e41be5e9ea96cf8bee5a1b4727b6493f7de21c
